// Generated by tools/upgrade_stanli.sh from nuts.cpp.
#include <stanli/nuts.hpp>

namespace stanli {

bool thread_safe_build() {
#ifdef STAN_THREADS
  return true;
#else
  return false;
#endif
}

}  // namespace stanli
