#!/bin/sh
# Vendors stanli (github.com/seantalts/stanli), following this package's
# convention for bundled libraries
set -e

STANLI_REF="e8d2c06"
STANLI_TARBALL="stanli-$STANLI_REF.tar.gz"
STANLI_URL="https://github.com/seantalts/stanli/archive/$STANLI_REF.tar.gz"

if [ ! -f "$STANLI_TARBALL" ]; then
  curl -sSL -o "$STANLI_TARBALL" "$STANLI_URL"
fi
tar -xf "$STANLI_TARBALL"
# Read the archive's single top-level directory rather than globbing the
# working tree: old upgrade snapshots are intentionally left here and would
# otherwise make STANLI_DIR contain multiple paths.
STANLI_DIR=$(tar -tf "$STANLI_TARBALL" | awk -F/ 'NF { print $1; exit }')
test -n "$STANLI_DIR" && test -d "$STANLI_DIR"

SRC=../src/stanli

rm -rf "$SRC"
# The PCH only depends on its umbrella header, not the vendored headers it
# includes.  Invalidate it so the next package build cannot reuse the prior
# stanli revision's cache.
rm -f ../src/include/stanli_pch.hpp.gch ../src/include/stanli_pch.hpp.pch
mkdir -p "$SRC/runtime"

cp -f "$STANLI_DIR/LICENSE" "$SRC/"

cp -Rf "$STANLI_DIR/runtime/include" "$SRC/runtime/"
cp -Rf "$STANLI_DIR/runtime/src" "$SRC/runtime/"
cp -Rf "$STANLI_DIR/runtime/kernels" "$SRC/runtime/"
rm -f "$SRC/runtime/include/stanli/README.md"

rm -f "$SRC/runtime/src/capi.cpp" \
      "$SRC/runtime/src/bridgestan_abi.cpp" \
      "$SRC/runtime/src/stanc_embed_c.cpp" \
      "$SRC/runtime/src/nuts.cpp" \
      "$SRC/runtime/src/estimate.cpp" \
      "$SRC/runtime/src/diagnose.cpp" \
      "$SRC/runtime/src/walnuts.cpp" \
      "$SRC/runtime/src/pathfinder.cpp" \
      "$SRC/runtime/src/data.cpp" \
      "$SRC/runtime/src/README.md" \
      "$SRC/runtime/src/OPTIMIZATIONS.md"
# Private helper for nuts.cpp/estimate.cpp/pathfinder.cpp only -- dead once
# all three algorithm frontends above are stripped.
rm -f "$SRC/runtime/src/initialize.hpp"
rm -f "$SRC/runtime/include/stanli/capi.h" \
      "$SRC/runtime/include/stanli/bridgestan_internal.hpp" \
      "$SRC/runtime/include/stanli/nuts.hpp" \
      "$SRC/runtime/include/stanli/estimate.hpp" \
      "$SRC/runtime/include/stanli/diagnose.hpp" \
      "$SRC/runtime/include/stanli/walnuts.hpp" \
      "$SRC/runtime/include/stanli/model_adapter.hpp"

python3 - "$SRC/runtime/include/stanli/optable.hpp" "$SRC/runtime/kernels" << 'EOF'
import glob
import os
import re
import sys

optable_path, kernels_dir = sys.argv[1], sys.argv[2]
text = open(optable_path).read()

def macro_body(name):
    # Everything after "#define NAME(X)" up to (and including) the first
    # line whose newline isn't escaped by a line-continuation backslash.
    m = re.search(r'#define\s+' + re.escape(name) + r'\(X\)(.*?)(?<!\\)\n',
                  text, re.S)
    assert m, f"{name}(X) not found -- optable.hpp changed upstream"
    return m.group(1)

# Discover the list's membership from STANLI_SCALAR_DENSITY_LIST(X)
# itself rather than naming its sub-lists, so a future reshuffle of the
# grouping upstream doesn't silently drop or duplicate a distribution.
sub_lists = re.findall(r'(STANLI_SCALAR_DENSITY_LIST_\w+)\(X\)',
                        macro_body("STANLI_SCALAR_DENSITY_LIST"))
assert sub_lists, ("no sub-lists in STANLI_SCALAR_DENSITY_LIST(X) -- "
                    "optable.hpp changed upstream")

entry_re = re.compile(
    r'X\(\s*([A-Z0-9_]+)\s*,\s*([a-z0-9_]+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)')
entries = []  # (code, fn, nargs, tier)
for sub in sub_lists:
    found = entry_re.findall(macro_body(sub))
    assert found, f"{sub}(X) has no entries -- optable.hpp changed upstream"
    entries.extend(found)

names = [fn for _, fn, _, _ in entries]
assert len(names) == len(set(names)), "a density name appears in two sub-lists"

# The files currently defining these entries are whatever kernels/*.cpp
# instantiate a density sub-list -- not a fixed filename list, since
# upstream is free to rename or regroup its shards.
shard_call_re = re.compile(
    r'STANLI_SCALAR_DENSITY_LIST_\w+\(STANLI_DEFINE_DENSITY_FWD\)')
old_shards = [p for p in glob.glob(os.path.join(kernels_dir, "*.cpp"))
              if shard_call_re.search(open(p).read())]
assert old_shards, ("no existing density shard files found -- "
                     "kernels/ layout changed upstream")
for p in old_shards:
    os.remove(p)

template = """// Generated by tools/upgrade_stanli.sh: one LPDF, one translation unit.
// See upgrade_stanli.sh for why -- grouping entries, even just the
// costliest two, does not amortize stan-math's per-distribution
// instantiation cost away.
#include "densities_impl.hpp"

namespace stanli {{
namespace dens {{

STANLI_DEFINE_DENSITY_FWD({code}, {fn}, {nargs}, {tier})

}}  // namespace dens
}}  // namespace stanli
"""
for code, fn, nargs, tier in entries:
    out_path = os.path.join(kernels_dir, f"densities_{fn}.cpp")
    assert not os.path.exists(out_path), f"{out_path} already exists"
    open(out_path, "w").write(
        template.format(code=code, fn=fn, nargs=nargs, tier=tier))
EOF

python3 - "$SRC/runtime/src/message_sink.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_include = "#include <cstdio>\n"
assert old_include in text, "cstdio include not found -- message_sink.cpp changed upstream"
text = text.replace(old_include, "", 1)

old_body = """  if (sink()) {
    sink()(text.data(), text.size());
    return;
  }
  // The default, and what both paths did before there was a sink: the
  // line and its newline to stdout. One fwrite per call rather than two,
  // so a line cannot be split by another thread's output.
  std::string line = text;
  line += '\\n';
  std::fwrite(line.data(), 1, line.size(), stdout);
}
"""
new_body = """  if (sink()) sink()(text.data(), text.size());
  // No sink installed: stanr does not call set_message_sink() (yet), and
  // the default fallback wrote to the process's raw stdout, which R CMD
  // check flags. Drop the message rather than write around R's console.
}
"""
assert old_body in text, "emit_message body not found -- message_sink.cpp changed upstream"
text = text.replace(old_body, new_body, 1)

# This TU's local sink() clashes with the unrelated struct stanli::sink
# (recorder.hpp) once src/Makevars's PCH forces recorder.hpp into every
# stanli translation unit -- ambiguous lookup, not visible when this file
# is compiled standalone. Rename the local one out of the way.
old_decl = "MessageSink& sink() {\n"
new_decl = "MessageSink& current_sink() {\n"
assert old_decl in text, "sink() declaration not found -- message_sink.cpp changed upstream"
text = text.replace(old_decl, new_decl, 1)

old_set = "  sink() = std::move(s);\n"
new_set = "  current_sink() = std::move(s);\n"
assert old_set in text, "set_message_sink() body not found -- message_sink.cpp changed upstream"
text = text.replace(old_set, new_set, 1)

old_emit = "  if (sink()) sink()(text.data(), text.size());\n"
new_emit = "  if (current_sink()) current_sink()(text.data(), text.size());\n"
assert old_emit in text, "emit_message() sink call not found -- message_sink.cpp changed upstream"
text = text.replace(old_emit, new_emit, 1)

open(path, "w").write(text)
EOF

# STANLI_DEBUG_ISLAND traces to stderr; stanr never sets it.
python3 - "$SRC/runtime/src/island.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_no_adjoint = """      // A refusal is not an error -- the replay still gives the right
      // gradient -- but it is worth being able to see, because it is the
      // difference between a region that is fast and one that merely
      // works, and nothing else about the model would show it.
      if (!priced_gen && std::getenv("STANLI_DEBUG_ISLAND"))
        std::fprintf(stderr,
                     "island: no adjoint generated for a %zu-op region; "
                     "it will replay under var\\n",
                     j - i);
    }
"""
new_no_adjoint = """    }
"""
assert old_no_adjoint in text, "no-adjoint debug trace not found -- island.cpp changed upstream"
text = text.replace(old_no_adjoint, new_no_adjoint, 1)

old_cost = """      if (std::getenv("STANLI_DEBUG_ISLAND"))
        std::fprintf(stderr, "island? ops=%zu graph=%lld island=%lld\\n", j - i,
                     (long long)graph_cost, (long long)island_cost);
      if (graph_cost < island_cost) compiled = false;
"""
new_cost = """      if (graph_cost < island_cost) compiled = false;
"""
assert old_cost in text, "island-cost debug trace not found -- island.cpp changed upstream"
text = text.replace(old_cost, new_cost, 1)

old_forwarding = """        } else if (std::getenv("STANLI_DEBUG_ISLAND")) {
          std::fprintf(stderr,
                       "island: destination forwarding kept the priced "
                       "program because its optimized adjoint was refused\\n");
        }
"""
new_forwarding = """        }
"""
assert old_forwarding in text, "destination-forwarding debug trace not found -- island.cpp changed upstream"
text = text.replace(old_forwarding, new_forwarding, 1)

old_carved = """      if (std::getenv("STANLI_DEBUG_ISLAND")) {
        const IslandProg& p = *static_cast<const IslandProg*>(is.udata);
        std::fprintf(stderr,
                     "island: ops=%zu instr=%zu regs=%d ins=%zu outs=%zu "
                     "adj=%zu adj_regs=%d\\n",
                     j - i, p.code.size(), p.n_regs, p.ins.size(),
                     p.out_regs.size(), p.adj.code.size(), p.adj.n_regs);
        // Which instructions the region is made of, so a disagreement
        // with the replay can be attributed to an opcode rather than
        // guessed at.
        std::vector<int> hist(64, 0);
        for (const auto& I : p.code)
          if ((int)I.code < 64) ++hist[(size_t)I.code];
        std::fprintf(stderr, "island opcodes:");
        for (int c = 0; c < 64; ++c)
          if (hist[(size_t)c])
            std::fprintf(stderr, " %d:%d", c, hist[(size_t)c]);
        std::fprintf(stderr, "\\n");
      }
      ++carved;
"""
new_carved = """      ++carved;
"""
assert old_carved in text, "carved-island debug trace not found -- island.cpp changed upstream"
text = text.replace(old_carved, new_carved, 1)

old_include = "#include <cstdio>\n"
assert old_include in text, "cstdio include not found -- island.cpp changed upstream"
text = text.replace(old_include, "", 1)

open(path, "w").write(text)
EOF

# STANLI_DEBUG_ODE traces to stderr; stanr never sets it.
python3 - "$SRC/runtime/src/lower.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

# Preparation profiling is an opt-in standalone-runtime diagnostic. stanr
# never enables it, and its report writes around R's console to raw stderr.
report_start = "  void report() const {\n"
report_end = "\n private:\n"
start = text.find(report_start)
assert start >= 0, "PrepTrace::report() not found -- lower.cpp changed upstream"
end = text.find(report_end, start)
assert end >= 0, "end of PrepTrace::report() not found -- lower.cpp changed upstream"
text = text[:start] + "  void report() const {}\n" + text[end:]

old_overflow = "    if (size_ >= rows_.size()) std::abort();\n"
new_overflow = "    if (size_ >= rows_.size()) return rows_.back();\n"
assert old_overflow in text, "PrepTrace overflow guard not found -- lower.cpp changed upstream"
text = text.replace(old_overflow, new_overflow, 1)

old_algebra = """    if (!spec->prog.ok && std::getenv("STANLI_DEBUG_ALGEBRA"))
      std::fprintf(stderr,
                   "stanli: algebraic system %s falls back to the "
                   "interpreter: %s\\n",
                   spec->system_name.c_str(), spec->prog.why.c_str());

"""
assert old_algebra in text, "algebra fallback debug trace not found -- lower.cpp changed upstream"
text = text.replace(old_algebra, "", 1)

old_doc = """  // The op tail both ODE families share: report an interpreter fallback,
  // emit OP_ODE and hand the spec to the graph.
"""
new_doc = """  // The op tail both ODE families share: emit OP_ODE and hand the spec
  // to the graph.
"""
assert old_doc in text, "emit_ode doc comment not found -- lower.cpp changed upstream"
text = text.replace(old_doc, new_doc, 1)

old_trace = """    // Falling back to the interpreter is correct but ~30x slower, so make
    // it findable rather than silent.
    if (!spec->prog.ok && std::getenv("STANLI_DEBUG_ODE"))
      std::fprintf(stderr,
                   "stanli: ODE right-hand side %s falls back to the "
                   "interpreter: %s\\n",
                   spec->rhs_name.c_str(), spec->prog.why.c_str());
"""
new_trace = ""
assert old_trace in text, "ODE fallback debug trace not found -- lower.cpp changed upstream"
text = text.replace(old_trace, new_trace, 1)

old_direct_rk = """    if (spec->prog.ok &&
        (spec->solver == OdeSpec::RK45 || spec->solver == OdeSpec::CKRK) &&
        std::getenv("STANLI_DEBUG_ODE")) {
      if (spec->direct_rk)
        std::fprintf(stderr,
                     "stanli: ODE right-hand side %s is direct-RK eligible%s\\n",
                     spec->rhs_name.c_str(),
                     spec->direct_rk_enabled ? "" : " (oracle selected)");
      else
        std::fprintf(stderr,
                     "stanli: ODE right-hand side %s keeps the RK oracle: %s\\n",
                     spec->rhs_name.c_str(), spec->direct_rk_why.c_str());
    }
"""
assert old_direct_rk in text, "direct-RK debug trace not found -- lower.cpp changed upstream"
text = text.replace(old_direct_rk, "", 1)

old_include = "#include <cstdio>\n"
assert old_include in text, "cstdio include not found -- lower.cpp changed upstream"
text = text.replace(old_include, "", 1)

open(path, "w").write(text)
EOF
